### PR TITLE
Update for compatibility with Omeka

### PR DESCRIPTION
**Pull request by timstallmann**
Hi! I'm so glad I found this plugin -- just a small PR to:
* Change the `plugin.php` file to be compatible with modern Omeka plugin syntax
* Upgrade dependencies
* Add a new `isObjectAvailable` method, which mirrors the method in the `Zend_S3` plugin (to check if an object exists).

### CODE REVIEW

**Comment by mikesname** [comment]
@timstallmann thanks! Does the `composer.json` file also need to be updated? Also, would you mind bumping the plugin version to something like `1.1.0` in the `plugin.ini` file in the patch?

**Comment by timstallmann** [comment]
Version number changed! And `composer.json` is fine as is, just the `composer.lock` needed to be changed -- `aws-sdk-php` is still on major version 3.

**Comment by mikesname** [comment]
@timstallmann I'm afraid I merged this a bit hastily yesterday and missed something.

Will it inconvenience you if I change the name of the class from `OmekaAmazonS3StorageAdapterPlugin` to just `AmazonS3StorageAdapterPlugin`? This is most plugins I'm aware of do not have the prefix, it's not an Omeka internal class, and it would also require us to reinstall rather than upgrade our many existing instances.

Sorry about that!

**Comment by timstallmann** [comment]
For sure, no problem, sorry about that!

**Pull request merged**
